DATA salida1(keep=CUENTA TIPO_MOV INDICADOR BANCO IDDOCX NUMDOCX TIPO_OPE CODI_OPE FECCAMB 
				CODTRAN FECHA_CONTA FECHA_OPER APLICACION_ORI NUMER_OPE NUMER_REF USERID_UMO TIMEST_UMO DIVISA);
SET X.ITCC;

*Cuenta, tipo de movimiento, Numero y tipo de documento;
IF IND_OPE in ('0','2') OR IDDOC='CT' THEN
	DO;	CUENTA=CCC;
		TIPO_MOV='04';
	END; 
ELSE IF APLICACION_ORI='CT' THEN
	DO;	CUENTA=CONTRATO_REF;
		TIPO_MOV='04';
	END; 
ELSE
	DO;	IDDOCX=IDDOC;
		NUMDOCX=NUMDOC;
		TIPO_MOV='03';
	END; 

*Indicador de Banco;
BANCO='CL';
IF NUMDOC='20100130204' then BANCO='BA';


*Codigo de operacion y tipo de operación;
*--Actualiza inciso y apendice;
IF CODOPE = '527  ' AND SubStr(APENDICE,1,2)='29' AND IMPORTE_IMPTO > 0 THEN
	DO; INCISO='01';
		APENDICE='   ';
	END;

IF INCISO = '' then
	do;
	TIPO_OPE='02';
	CODI_OPE=APENDICE;
	end;
ELSE 
	do;
	TIPO_OPE='01';
	CODI_OPE=INCISO;
	end;

*Variables de paso;
CODTRAN=CODTRAN_UMO;
*FECHA_CONTA, FECHA_OPER, APLICACION_ORI, NUMER_OPE, NUMER_REF, USERID_UMO TIMEST_UMO DIVISA;

*Fecha de Tipo de cambio;
IF IMPORTE_IMPTO < 0 and FECHA_REFE NE '0001-01-01' THEN
	FECCAMB=FECHA_REFE;
ELSE
	FECCAMB=FECHA_CONTA;

*Factor de Tipo de cambio (CAMBBAJO/CTUNICAM): Se obtiene desde TC9C1810, INDDIVBI='P';


*Pendiente;
INDICADOR=IND_OPE;
RUN;




